import type { OSITFormulaId, OSITFormulaOperator, OSITRuntimeModule } from "./ositTypes";

export const OSIT_FORMULA_REGISTRY: Record<OSITFormulaId, OSITFormulaOperator> = {
  shannon_entropy: {
    id: "shannon_entropy",
    label: "Shannon entropy",
    historicalReference: "Shannon",
    boundary: "NUMERIC_APPROXIMATION",
    modules: ["MTS", "R", "Phi_eff", "WitnessLog", "LanguageCortex"],
    implementationStatus: "implemented_proxy",
    risk: 0.12,
    Phi_eff: 0.86,
    publicClaimAllowed: false,
    notes: "Used to estimate signal uncertainty and residue pressure; not a universal consciousness proof.",
  },
  boltzmann_entropy: {
    id: "boltzmann_entropy",
    label: "Boltzmann entropy",
    historicalReference: "Boltzmann",
    boundary: "OPERATIONAL_METAPHOR",
    modules: ["R", "J_c", "PixelLightEngine", "BrainRuntime"],
    implementationStatus: "implemented_proxy",
    risk: 0.18,
    Phi_eff: 0.78,
    publicClaimAllowed: false,
    notes: "Maps microstate growth to residue/jamming pressure in simulation state.",
  },
  maxwell_field_proxy: {
    id: "maxwell_field_proxy",
    label: "Maxwell field proxy",
    historicalReference: "Maxwell",
    boundary: "FORMAL_LAB_ONLY",
    modules: ["PixelLightEngine", "CausalRendering", "AudioGameFeel"],
    implementationStatus: "mapped_contract",
    risk: 0.24,
    Phi_eff: 0.72,
    publicClaimAllowed: false,
    notes: "Field coupling language for light/audio transduction; physically inspired approximation only.",
  },
  navier_stokes_flow_proxy: {
    id: "navier_stokes_flow_proxy",
    label: "Navier-Stokes flow proxy",
    historicalReference: "Navier-Stokes",
    boundary: "NUMERIC_APPROXIMATION",
    modules: ["PixelLightEngine", "CausalRendering", "RPGBridge"],
    implementationStatus: "implemented_proxy",
    risk: 0.21,
    Phi_eff: 0.74,
    publicClaimAllowed: false,
    notes: "Sparse active-cell proxy for water/smoke flow; not full fluid simulation.",
  },
  fourier_signal_decomposition: {
    id: "fourier_signal_decomposition",
    label: "Fourier signal decomposition",
    historicalReference: "Fourier",
    boundary: "NUMERIC_APPROXIMATION",
    modules: ["AudioGameFeel", "MTS", "WitnessLog"],
    implementationStatus: "implemented_proxy",
    risk: 0.1,
    Phi_eff: 0.88,
    publicClaimAllowed: false,
    notes: "Used for signal/tempo energy summaries in procedural audio and MTS timing.",
  },
  schrodinger_probability_boundary: {
    id: "schrodinger_probability_boundary",
    label: "Schrodinger probability boundary",
    historicalReference: "Schrodinger",
    boundary: "IN_WORLD_LORE",
    modules: ["GhostGate", "CausalRendering", "RPGBridge"],
    implementationStatus: "reference_only",
    risk: 0.34,
    Phi_eff: 0.64,
    publicClaimAllowed: false,
    notes: "Narrative uncertainty and observation boundary only; no quantum physics claim.",
  },
  black_scholes_risk_proxy: {
    id: "black_scholes_risk_proxy",
    label: "Black-Scholes risk proxy",
    historicalReference: "Black-Scholes",
    boundary: "OPERATIONAL_METAPHOR",
    modules: ["ActionGate", "R", "J_c"],
    implementationStatus: "implemented_proxy",
    risk: 0.16,
    Phi_eff: 0.8,
    publicClaimAllowed: false,
    notes: "Risk/options metaphor for Apply/rollback/gate pressure, not financial advice.",
  },
  euler_step: {
    id: "euler_step",
    label: "Euler step",
    historicalReference: "Euler",
    boundary: "NUMERIC_APPROXIMATION",
    modules: ["MTS", "PixelLightEngine", "BrainRuntime"],
    implementationStatus: "implemented_proxy",
    risk: 0.08,
    Phi_eff: 0.9,
    publicClaimAllowed: false,
    notes: "Simple deterministic integration step for local ticks.",
  },
  gauss_evidence_weight: {
    id: "gauss_evidence_weight",
    label: "Gauss evidence weight",
    historicalReference: "Gauss",
    boundary: "NUMERIC_APPROXIMATION",
    modules: ["WitnessLog", "Phi_eff", "TruthGate"],
    implementationStatus: "implemented_proxy",
    risk: 0.1,
    Phi_eff: 0.86,
    publicClaimAllowed: false,
    notes: "Gaussian-style weighting for evidence confidence and outlier handling.",
  },
  newton_motion_proxy: {
    id: "newton_motion_proxy",
    label: "Newton motion proxy",
    historicalReference: "Newton",
    boundary: "NUMERIC_APPROXIMATION",
    modules: ["PixelLightEngine", "CausalRendering", "RPGBridge"],
    implementationStatus: "implemented_proxy",
    risk: 0.12,
    Phi_eff: 0.84,
    publicClaimAllowed: false,
    notes: "Finite motion proxy for agents/material gameplay, not exact physical simulation.",
  },
};

export function listOSITFormulaOperators(): OSITFormulaOperator[] {
  return Object.values(OSIT_FORMULA_REGISTRY);
}

export function mapFormulaToOSITModule(module: OSITRuntimeModule): OSITFormulaOperator[] {
  return listOSITFormulaOperators().filter(formula => formula.modules.includes(module));
}
