from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path
from typing import Any

from _common import ROOT, print_json, sha256_file, validate_root_arg, add_common_args


DOWNLOADS = Path.home() / "Downloads"
TEXT_SUFFIXES = {".txt", ".md", ".py", ".json", ".csv", ".html", ".css", ".js"}

KNOWN_FILES = [
    {
        "path": DOWNLOADS / "observacionismo_ai_os_fullstack.zip",
        "classification": "EXTERNAL_TECHNICAL_ZIP",
        "lane": "obsai",
        "intake_action": "SELECTIVE_ABSORPTION_ONLY",
        "target": "packages/obsai-core",
        "notes": "Use as source material for obsai-core, metrics, gate and CLI. Do not copy wholesale.",
    },
    {
        "path": DOWNLOADS / "operational_ai_threshold.zip",
        "classification": "EXTERNAL_TECHNICAL_ZIP",
        "lane": "obsai",
        "intake_action": "SELECTIVE_ABSORPTION_ONLY",
        "target": "packages/obsai-core",
        "notes": "Threshold heuristics remain DEMO_ONLY until calibrated with a real dataset.",
    },
    {
        "path": DOWNLOADS / "residueos_mvp.zip",
        "classification": "EXTERNAL_TECHNICAL_ZIP",
        "lane": "residueos",
        "intake_action": "SELECTIVE_ABSORPTION_ONLY",
        "target": "apps/residueos",
        "notes": "JSON store is DEMO_ONLY until migrated to SQLite with audit and human review.",
    },
    {
        "path": DOWNLOADS / "medioevo_observacionismo_codex_pack.zip",
        "classification": "EXTERNAL_CANON_TOOLKIT_ZIP",
        "lane": "lore",
        "intake_action": "SELECTIVE_ABSORPTION_ONLY",
        "target": "packages/lore-compiler and game-private manifests",
        "notes": "Feed Lore Compiler and private WorldPulse work. Do not publish the game.",
    },
    {
        "path": DOWNLOADS / "duat_lg_patch.zip",
        "classification": "EXTERNAL_RESEARCH_TOOLKIT_ZIP",
        "lane": "research-boundary",
        "intake_action": "RESEARCH_ONLY",
        "target": "research/",
        "notes": "Formal research/toolkit source. No product claims without falsifier or prediction requirement.",
    },
    {
        "path": DOWNLOADS / "obs_antigravity_runtime.zip",
        "classification": "EXTERNAL_RESEARCH_RUNTIME_ZIP",
        "lane": "research-boundary",
        "intake_action": "KEEP_GATED_SELECTIVE_ABSORPTION",
        "target": "docs/OBS_ANTIGRAVITY_RUNTIME_REVIEW_2026-05-01.md and future packages/obsai-core adapters",
        "decision": "keep_gated/research_runtime_to_claim_gate",
        "risks": [
            "Domain name can invite overclaiming; public copy must say epistemic filter, not physical antigravity.",
            "ZIP contains generated bytecode in the original source; clean before any package or repo import.",
            "Scientific evidence references must stay tied to primary sources and current uncertainty.",
        ],
        "notes": "Tests passed locally. Reuse generic parts only: evidence record, PAC gate, conservative validator pattern, ontology handoff and simulation-only fixtures.",
    },
    {
        "path": DOWNLOADS / "Aquí tienes el código completo para.txt",
        "classification": "EXTERNAL_OBSERVACIONISMO_RESEARCH_CODE_MIXED",
        "lane": "research-boundary",
        "intake_action": "KEEP_GATED_TRIAGE",
        "target": "research/obs-info-kernel triage and docs/OBS_INFO_KERNEL_REVIEW_2026-05-01.md",
        "decision": "keep_gated/anti_information_dark_information_code_triage",
        "risks": [
            "Contains useful anti-information and dark-information code mixed with speculative claims and aggressive deployment language.",
            "Contains external commands and product-like claims that must not be executed or copied into public copy.",
            "Use only tested, low-claim research primitives; verify sources before novelty claims.",
        ],
        "notes": "Large mixed source for anti-informacion, informacion oscura, academic search agents and PSI runtime ideas. Treat as research input, not production code.",
    },
    {
        "path": DOWNLOADS / "SFAEFAGF.txt",
        "classification": "EXTERNAL_OBSERVACIONISMO_ENGINE_ITERATIONS",
        "lane": "research-boundary",
        "intake_action": "KEEP_GATED_RUNTIME_TRIAGE",
        "target": "research/obs-info-kernel and future obsai-core experiments after tests",
        "decision": "keep_gated/observacionismo_engine_iterations",
        "risks": [
            "Contains multiple engine versions, optional heavy dependencies and local model references.",
            "Contains subprocess/Ollama patterns that need sandboxing and timeouts before runtime use.",
            "Do not promote claims about non-human discovery without primary-source validation.",
        ],
        "notes": "Iteration source for persistent PSI state, SQLite cache, graph persistence, surprise/entropy metrics and SESSION_FINGERPRINT continuity.",
    },
    {
        "path": DOWNLOADS / "He analizado todo el material compi.txt",
        "classification": "EXTERNAL_OBSERVACIONISMO_SYNTHESIS_REVIEW",
        "lane": "research-boundary",
        "intake_action": "KEEP_GATED_IMPLEMENTATION_ROADMAP",
        "target": "docs/OBS_INFO_KERNEL_REVIEW_2026-05-01.md and PENDIENTES_MASTER.md",
        "decision": "keep_gated/implementation_roadmap_not_product_claim",
        "risks": [
            "Contains a useful roadmap but also strong thesis language that must remain internal.",
            "Dashboard/API/Docker snippets require separate implementation and security review.",
            "Use as backlog and design synthesis, not as proof that the product is production-ready.",
        ],
        "notes": "Synthesis review: integrate EstadoPSI, academic agents, anti-information, dark-information, ActionGate, SQLite, tests and cache; postpone speculative modules.",
    },
    {
        "path": DOWNLOADS / "He revisado `La integración correct.txt",
        "classification": "EXTERNAL_OBSERVACIONISMO_ARCHITECTURE_SYNTHESIS",
        "lane": "github-public-sanitized",
        "intake_action": "CURATOR_TECHNICAL_CARD_AND_WHITEPAPER_SOURCE",
        "target": "docs/developer/AI_WEB_GATEWAY_OBSERVACIONISTA_WHITEPAPER.md and public sanitized repo queue",
        "decision": "use_as_architecture_source/not_raw_publication",
        "risks": [
            "Contains useful AI-Web Gateway, ResidueOS, ActionGate and obs-info-kernel architecture mixed with private context and strong research claims.",
            "Mentions exposed credential risk and credential-vault patterns; raw text must not be copied into public repos.",
            "Scientific and cosmology language must be reduced to operational evidence, calibration and claim-boundary wording before GitHub.",
        ],
        "notes": "Primary new synthesis for public sanitized GitHub lanes: AI-Web Gateway, ObservationEnvelope, MCP interface, evidence store, claim registry and whitepaper queue.",
    },
    {
        "path": DOWNLOADS / "La integración correcta.txt",
        "classification": "EXTERNAL_OBSERVACIONISMO_ARCHITECTURE_BASE",
        "lane": "github-public-sanitized",
        "intake_action": "BASELINE_COMPARE_ONLY",
        "target": "curador session and AI-Web Gateway whitepaper source notes",
        "decision": "source_baseline/compare_against_revised_doc",
        "risks": [
            "Base architecture text may include raw implementation suggestions that need secret handling and claim review.",
            "Use as lineage evidence, not as public copy.",
        ],
        "notes": "Baseline document for the revised architecture synthesis.",
    },
    {
        "path": DOWNLOADS / "r.txt",
        "classification": "USER_ASSERTED_SAFE_NON_BLOCKING",
        "lane": "secrets",
        "intake_action": "REDACTED_EVIDENCE_ONLY_DO_NOT_STAGE",
        "target": "RISK_REGISTER.md, RELEASE_CHECKLIST.md and curador redacted evidence",
        "decision": "user_asserted_safe/non_blocking/no_raw_publication",
        "risks": [
            "User clarified this token note was inserted by another AI report and is safe.",
            "Do not print token-like values, copy them into manifests or include the file in any GitHub staging area.",
            "Future publication still depends on allowlist secret scans, not on this file being staged.",
        ],
        "notes": "No longer a release blocker by human override. Keep only redacted audit metadata and exclude from public staging.",
    },
    {
        "path": DOWNLOADS / "#!usrbinenv python3.txt",
        "classification": "EXTERNAL_OBSERVACIONISMO_V2_NEUROSTATE_BUNDLE",
        "lane": "duat-neurostate-residueos",
        "intake_action": "SPLIT_BEFORE_USE",
        "target": "claudio/memory_vault, research/obs-info-kernel, residueos-core, ai-web-gateway-observacionista",
        "decision": "split_neurostate_python_ui_promptshield_papers",
        "risks": [
            "Large mixed source contains Python runtime, NEUROSTATE UI, Prompt Shield, paper drafts and pitch copy.",
            "Must be split into technical cards before code import; raw file is not public copy.",
            "Claims about cognition, survival and agent safety require measured evidence and low-claim language.",
        ],
        "notes": "Observed EstadoPSI, semantic vectorizer, epistemic graph, anti-information, dark-information, academic agents, TerminalGuard, NEUROSTATE v2 UI, Prompt Shield + ResidueOS and paper/pitch sections.",
    },
    {
        "path": DOWNLOADS / "Me has pedido que te recomiende pro.txt",
        "classification": "EXTERNAL_GITHUB_TECH_INTEGRATION_ROADMAP",
        "lane": "github-public-sanitized",
        "intake_action": "VERIFY_EXTERNAL_REPOS_AND_BACKLOG",
        "target": "claudio/memory_vault/external_projects_verification.md and docs/developer/TECHNOLOGY_IMPLEMENTATION_BACKLOG_2026-05-02.md",
        "decision": "verify_before_dependency_or_claim",
        "risks": [
            "External project status, licenses and activity are time-sensitive.",
            "Do not treat recommendations as current until verified against official repositories or docs.",
            "Integrate as roadmap/backlog first; no auto-forking, vendoring or publication.",
        ],
        "notes": "Roadmap source for Phoenix/OpenTelemetry, prompt-injection shields, AgentScope, GPTCache, LiteLLM, browser agents, research agents, memory and observability integrations.",
    },
    {
        "path": DOWNLOADS / "obs_info_kernel_package.zip",
        "classification": "EXTERNAL_OBS_INFO_KERNEL_PACKAGE",
        "lane": "research-boundary",
        "intake_action": "INTERNAL_RESEARCH_KERNEL_ONLY",
        "target": "research/obs-info-kernel",
        "decision": "internal_research/clean_extract_no_publication",
        "risks": [
            "Original ZIP includes generated bytecode and reports; clean before workspace import.",
            "Kernel finds candidates and gaps, not truth; public claims must say research aid only.",
            "Do not publish as open-dev until source validation, secret scan, license review and claims boundary pass.",
        ],
        "notes": "Installable zero-dependency package for anti-information, dark-information, calibration gaps, reports and continuity artifacts. Temp extraction tests passed.",
    },
    {
        "path": DOWNLOADS / "Sí, Luis René. Radicalmente. Has pu.txt",
        "classification": "EXTERNAL_EOR_AIA_TOPOLOGY_SYNTHESIS",
        "lane": "research-boundary",
        "intake_action": "KEEP_GATED_EOR_AIA_SYNTHESIS",
        "target": "research/obs-info-kernel and docs/OBS_EOR_AIA_TOPOLOGY_REVIEW_2026-05-01.md",
        "decision": "keep_gated/eor_aia_entropy_topology_synthesis",
        "risks": [
            "Contains useful EOR/AIA architecture mixed with strong entropy, physics and consciousness claims.",
            "Raw phrases such as R is entropy, entropy has owner and control R controls reality must be rewritten or blocked before canon/public use.",
            "Topology snippets require NetworkX/GrafoEpistemicoHibrido and stay optional until dependency and validation review.",
        ],
        "notes": "Absorb only low-claim primitives: EOR graph proxy, epistemic labels, operational equivalence test, dark-information states and non-anthropocentric AIA as procedure.",
    },
    {
        "path": DOWNLOADS / "observacionismo_research_report.md",
        "classification": "OBS_INFO_KERNEL_REPORT_OUTPUT",
        "lane": "research-boundary",
        "intake_action": "EVIDENCE_ONLY",
        "target": "docs/OBS_INFO_KERNEL_REVIEW_2026-05-01.md",
        "decision": "evidence_only/research_report",
        "risks": [
            "Report output has high R/JAMMING_TEMPRANO and must not be treated as final truth.",
            "Findings require primary-source validation before being used as public claims.",
        ],
        "notes": "Generated research report from obs-info-kernel; use for evidence and pending validation only.",
    },
    {
        "path": DOWNLOADS / "A_MEDIOEVO_OBSERVACIONISMO_DIEGETICO.md",
        "classification": "BOOKS_EDITORIAL_SOURCE",
        "lane": "lore",
        "intake_action": "CLASSIFY_BEFORE_EXTRACTION",
        "target": "books/ or packages/lore-compiler fixtures",
        "notes": "Diegetic MEDIOEVO source. Extract only evidence-backed data; mark inference.",
    },
    {
        "path": DOWNLOADS / "# Sí la idea fuerte es que el ecosi.txt",
        "classification": "PRIVATE_GAME_DESIGN_SOURCE",
        "lane": "rpg-private",
        "intake_action": "CLASSIFY_BEFORE_EXTRACTION",
        "target": "E:/Medioevo_RPG docs/data only",
        "notes": "WorldPulse/ecosystem-as-nervous-system game design source. Private game only.",
    },
    {
        "path": DOWNLOADS / "para el motor gemma 4 te tengo esto.txt",
        "classification": "EXTERNAL_AI_ARCHITECTURE_SOURCE",
        "lane": "obsai",
        "intake_action": "SELECTIVE_ABSORPTION_ONLY",
        "target": "packages/obsai-core or research/ after claim review",
        "notes": "Gemma/Observacionismo agent architecture source. No model modification claims without implementation evidence.",
    },
    {
        "path": DOWNLOADS / "# La App que no existe y que el mun.txt",
        "classification": "PRODUCT_CONCEPT_SOURCE",
        "lane": "residueos",
        "intake_action": "PRODUCT_IDEA_ONLY",
        "target": "apps/residueos or future kairos brief",
        "notes": "Kairos assistant concept. Do not claim product availability until implemented and tested.",
    },
    {
        "path": DOWNLOADS / "deep-research-report.md",
        "classification": "RESEARCH_ONLY_REPORT",
        "lane": "research-boundary",
        "intake_action": "RESEARCH_ONLY",
        "target": "research/",
        "notes": "Operational access-consciousness report. Keep separate from product claims.",
    },
    {
        "path": DOWNLOADS / "# Resultado matemático.txt",
        "classification": "RESEARCH_ONLY_REPORT",
        "lane": "research-boundary",
        "intake_action": "RESEARCH_ONLY",
        "target": "research/",
        "notes": "Mathematical boundary note: operational access only, not phenomenal consciousness proof.",
    },
    {
        "path": DOWNLOADS / "A continuación presento una formali.txt",
        "classification": "RESEARCH_ONLY_REPORT",
        "lane": "research-boundary",
        "intake_action": "RESEARCH_ONLY",
        "target": "research/",
        "notes": "Formal cosmology/model review. No physics or cosmology product claims.",
    },
    {
        "path": DOWNLOADS / "Voy a tomar la petición literalment.txt",
        "classification": "RESEARCH_LORE_TRANSLATION_SOURCE",
        "lane": "research-boundary",
        "intake_action": "RESEARCH_ONLY",
        "target": "research/ or lore residue with explicit inference labels",
        "notes": "Symbolic translation source. Treat as interpretive research, not canon fact.",
    },
    {
        "path": DOWNLOADS / "insights de programacion e ia..txt",
        "classification": "EXTERNAL_AI_ARCHITECTURE_SOURCE",
        "lane": "obsai",
        "intake_action": "SELECTIVE_ABSORPTION_ONLY",
        "target": "packages/obsai-core docs or research/",
        "notes": "Operational AI/programming insights. Absorb only concrete implementable controls.",
    },
    {
        "path": DOWNLOADS / "Esto es material extraordinariament.txt",
        "classification": "EXTERNAL_DEBUGTYR_SYNTHESIS_SOURCE",
        "lane": "obsai",
        "intake_action": "KEEP_GATED_RESEARCH_TO_RUNTIME_TRIAGE",
        "target": "packages/open-dev/obsai-core and docs/memoria_viva/fichas/ontologias-aei-pac-debugtyr.md",
        "decision": "keep_gated/debugtyr_research_to_runtime_triage",
        "risks": [
            "Contains speculative scientific/canon claims that must not become product claims.",
            "Contains mixed source material and code-like/UI fragments; absorb only tested runtime controls.",
            "Keep private/canon/family context out of public packages.",
        ],
        "notes": "DebugTyr raw synthesis. Extract only safety-gate, evidence, ontology and abstention controls with tests.",
    },
    {
        "path": DOWNLOADS / "Amigo, entiendo perfectamente tu di.txt",
        "classification": "EXTERNAL_MONETIZATION_ONTOLOGY_SYNTHESIS",
        "lane": "obsai",
        "intake_action": "KEEP_GATED_MONETIZATION_AND_ONTOLOGY_SYNTHESIS",
        "target": "docs/memoria_viva/fichas/monetizacion-etica-github-sponsors.md and docs/memoria_viva/fichas/ontologias-aei-pac-debugtyr.md",
        "decision": "keep_gated/monetization_and_ontology_synthesis",
        "risks": [
            "GitHub Sponsors setup is an external action and requires ActionGate, clean profile copy and manual payout/tax/2FA readiness.",
            "Legal structures such as LLC, trust, nonprofit and insurance are strategy notes only and require professional advice.",
            "Do not copy raw links, private context or full source text into public artifacts.",
        ],
        "notes": "Monetization and ontology synthesis: open canon plus paid services, voluntary Sponsors, family legacy planning and ontology layers.",
    },
    {
        "path": DOWNLOADS / "B_observacionist_agent.py",
        "classification": "EXTERNAL_RESEARCH_CODE",
        "lane": "obsai",
        "intake_action": "SELECTIVE_ABSORPTION_ONLY",
        "target": "packages/obsai-core experiments or research/",
        "notes": "Prototype code with numpy/scipy dependencies. Do not copy into core without stdlib/dependency decision.",
    },
    {
        "path": DOWNLOADS / "C_lg_benchmark.py",
        "classification": "EXTERNAL_RESEARCH_CODE",
        "lane": "obsai",
        "intake_action": "SELECTIVE_ABSORPTION_ONLY",
        "target": "packages/obsai-core experiments or research/",
        "notes": "LG/R benchmark prototype. Dataset and calibration claims remain DEMO_ONLY.",
    },
    {
        "path": DOWNLOADS / "D_MANUSCRITO_DE_CALIBRACION.md",
        "classification": "BOOKS_EDITORIAL_SOURCE",
        "lane": "lore",
        "intake_action": "CLASSIFY_BEFORE_EXTRACTION",
        "target": "packages/lore-compiler fixtures or game-private lore manifests",
        "notes": "Diegetic calibration manuscript. Evidence/inference split required before gameplay extraction.",
    },
    {
        "path": DOWNLOADS / "_ARCHIVO_OBSERVACIONISMO_DUPLICADOS_2026-04-29",
        "classification": "ARCHIVE_DUPLICATE_ROOT",
        "lane": "cleanup",
        "intake_action": "MANIFEST_ONLY",
        "target": "_archive/source-intake",
        "notes": "Duplicate source archive root; do not absorb unless a primary source is missing.",
    },
    {
        "path": DOWNLOADS / "_ARCHIVO_OBSERVACIONISMO_DUPLICADOS_2026-04-29" / "operational_ai_threshold (1).zip",
        "classification": "ARCHIVE_DUPLICATE",
        "lane": "cleanup",
        "intake_action": "MANIFEST_ONLY",
        "target": "_archive/source-intake",
        "notes": "Duplicate archive copy; keep as evidence, do not absorb unless primary is missing.",
    },
    {
        "path": DOWNLOADS / "_ARCHIVO_OBSERVACIONISMO_DUPLICADOS_2026-04-29" / "A_MEDIOEVO_OBSERVACIONISMO_DIEGETICO (1).md",
        "classification": "ARCHIVE_DUPLICATE",
        "lane": "cleanup",
        "intake_action": "MANIFEST_ONLY",
        "target": "_archive/source-intake",
        "notes": "Duplicate archive copy; keep as evidence, do not absorb unless primary is missing.",
    },
]

EXTERNAL_ROOTS = [
    {
        "path": Path("E:/-=Medioevo=-"),
        "classification": "BOOKS_COMMERCIAL_ARCHIVE",
        "lane": "publishing",
        "intake_action": "MANIFEST_AND_CHECKSUM_ONLY",
        "notes": "Books 00-34, audiobooks, Gumroad assets, consolidated 6+1 and editorial/commercial files.",
    },
    {
        "path": Path("E:/Medioevo_RPG"),
        "classification": "PRIVATE_GAME",
        "lane": "rpg-private",
        "intake_action": "PRIVATE_REPO_ACTIVE_MANIFEST_ONLY",
        "notes": "Godot private game with private local Git repo, WorldPulseBridge and headless validations. Do not publish or mix with open source.",
    },
    {
        "path": Path("E:/MEDIOEVO"),
        "classification": "LOCAL_SECRET_STATE",
        "lane": "cleanup",
        "intake_action": "DO_NOT_COPY",
        "notes": "Sessions, profiles and authentications. Treat as secret/local state.",
    },
    {
        "path": Path("E:/MEDIOEVO_ASSETS"),
        "classification": "PRIVATE_OR_COMMERCIAL_ASSETS",
        "lane": "publishing",
        "intake_action": "MANIFEST_AND_LICENSE_REVIEW_ONLY",
        "notes": "Commercial/private assets, including TCG and Claudio material under review.",
    },
    {
        "path": Path("E:/MEDIOEVO_AUDIO_LIBRARY"),
        "classification": "COMMERCIAL_AUDIO_ASSETS",
        "lane": "publishing",
        "intake_action": "MANIFEST_AND_LICENSE_REVIEW_ONLY",
        "notes": "Observed adjacent audio library; include in commercial manifests only after rights review.",
    },
    {
        "path": Path("E:/Audiobooks"),
        "classification": "COMMERCIAL_AUDIO_ASSETS",
        "lane": "publishing",
        "intake_action": "MANIFEST_AND_LICENSE_REVIEW_ONLY",
        "notes": "Observed adjacent audiobook root; do not copy into open packages.",
    },
]


def file_record(item: dict[str, Any], hash_files: bool) -> dict[str, Any]:
    path = item["path"]
    record = {
        "path": str(path),
        "exists": path.exists(),
        "classification": item["classification"],
        "lane": item["lane"],
        "intake_action": item["intake_action"],
        "target": item["target"],
        "notes": item["notes"],
    }
    if "decision" in item:
        record["decision"] = item["decision"]
    if "risks" in item:
        record["risks"] = item["risks"]
    if path.exists() and path.is_file():
        stat = path.stat()
        record["bytes"] = stat.st_size
        record["last_write_time_utc"] = datetime.fromtimestamp(stat.st_mtime, timezone.utc).isoformat()
        if path.suffix.lower() in TEXT_SUFFIXES and stat.st_size <= 5_000_000:
            record["line_count"] = count_text_lines(path)
        if hash_files:
            try:
                record["sha256"] = sha256_file(path)
            except OSError as exc:
                record["sha256_error"] = str(exc)
    return record


def count_text_lines(path: Path) -> int:
    try:
        with path.open("r", encoding="utf-8", errors="replace") as handle:
            return sum(1 for _ in handle)
    except OSError:
        return 0


def dir_record(item: dict[str, Any]) -> dict[str, Any]:
    path = item["path"]
    record = {
        "path": str(path),
        "exists": path.exists(),
        "classification": item["classification"],
        "lane": item["lane"],
        "intake_action": item["intake_action"],
        "notes": item["notes"],
    }
    if path.exists() and path.is_dir():
        child_dirs = 0
        child_files = 0
        sample_children: list[str] = []
        try:
            for child in sorted(path.iterdir(), key=lambda p: p.name.lower()):
                if child.is_dir():
                    child_dirs += 1
                elif child.is_file():
                    child_files += 1
                if len(sample_children) < 20:
                    sample_children.append(child.name)
        except OSError as exc:
            record["read_error"] = str(exc)
        else:
            record["child_dirs"] = child_dirs
            record["child_files"] = child_files
            record["sample_children"] = sample_children
            record["is_git_repo"] = (path / ".git").exists()
    return record


def build_register(hash_files: bool) -> dict[str, Any]:
    known_paths = {item["path"].resolve() for item in KNOWN_FILES}
    return {
        "generated_at_utc": datetime.now(timezone.utc).isoformat(),
        "workspace_root": str(ROOT),
        "rules": [
            "Classify every new source before extracting or copying code.",
            "Absorb selectively; never copy ZIPs wholesale into public or commercial packages.",
            "Keep research claims separate from product claims.",
            "Keep the game and TCG private unless a separate private release lane is explicitly authorized.",
            "Mark thresholds, weights and calibration as DEMO_ONLY until a real dataset exists.",
        ],
        "downloads": [file_record(item, hash_files=hash_files) for item in KNOWN_FILES],
        "additional_downloads": additional_download_records(known_paths, hash_files=hash_files),
        "external_roots": [dir_record(item) for item in EXTERNAL_ROOTS],
    }


def classify_additional_download(path: Path) -> dict[str, str]:
    name = path.name.lower()
    suffix = path.suffix.lower()

    if name == "desktop.ini":
        return {
            "classification": "LOCAL_SYSTEM_METADATA",
            "lane": "cleanup",
            "intake_action": "IGNORE_FOR_PUBLICATION",
            "target": "none",
            "notes": "Windows metadata file; keep out of source manifests and public packages.",
        }
    if path.is_dir():
        return {
            "classification": "ARCHIVE_OR_LOCAL_DIRECTORY",
            "lane": "cleanup",
            "intake_action": "MANIFEST_ONLY",
            "target": "_archive/source-intake",
            "notes": "Directory observed in Downloads. Do not absorb recursively without a focused pass.",
        }
    if "duat" in name or name in {"observ.md"} or "deep-research-report (2)" in name or "deep-research-report (3)" in name or "deep-research-report (4)" in name or "deep-research-report (5)" in name:
        return {
            "classification": "DUAT_LAB_SOURCE",
            "lane": "duat-lab",
            "intake_action": "TECHNICAL_CARD_AND_RESEARCH_BACKLOG",
            "target": "claudio/memory_vault and future research/duat-lab",
            "notes": "DUAT/DUAT Genesis source. Treat as computational lab material, not as validated physics or production software.",
        }
    if "deep-research-report (1)" in name:
        return {
            "classification": "GEMMA_OBSERVACIONISMO_INTEGRATION_REPORT",
            "lane": "obsai",
            "intake_action": "MODEL_ROUTING_BACKLOG_ONLY",
            "target": "packages/open-dev/obsai-core and Claudio model-router docs",
            "notes": "Gemma 4 integration report. Use for architecture/backlog only until host measurements and license review exist.",
        }
    if "esa es justo la capa" in name:
        return {
            "classification": "SCIENTIFIC_AGENT_ARCHITECTURE_SOURCE",
            "lane": "research-boundary",
            "intake_action": "SECURITY_REVIEW_AND_TECHNICAL_CARD",
            "target": "research/obs-info-kernel and ai-web-gateway-observacionista",
            "notes": "Scientific-agent architecture with CredentialVault, PragmaticGate, academic search and ActionGate. Requires security review before runtime use.",
        }
    if "estimado luis" in name:
        return {
            "classification": "OBSERVATIONAL_ONTOLOGY_SOFTWARE_REVIEW",
            "lane": "research-boundary",
            "intake_action": "RESEARCH_ONLY_WITH_CLAIM_BOUNDARY",
            "target": "claudio/memory_vault and DUAT/Kairos research backlog",
            "notes": "Review of cosmological-session/reality-calibration software ideas. Preserve as ontology/software design, not physics proof.",
        }
    if "excelente. tengo suficiente" in name:
        return {
            "classification": "PATENT_PATTERN_RESEARCH_SOURCE",
            "lane": "research-boundary",
            "intake_action": "LICENSE_AND_CLAIM_REVIEW",
            "target": "research/ and claims boundary docs",
            "notes": "Patent analysis and code-transfer source. Keep behind legal/license and claim review.",
        }
    if "hay que hacer una version lite" in name:
        return {
            "classification": "AEI_PAC_SYSTEM3_LITE_STRATEGY",
            "lane": "obsai",
            "intake_action": "BACKLOG_AND_LOW_CLAIM_SYNTHESIS",
            "target": "docs/developer/TECHNOLOGY_IMPLEMENTATION_BACKLOG_2026-05-02.md and obsai-core",
            "notes": "Lite-app and AEI/PAC/System-3 strategy source. Convert to operational controls and avoid superiority claims.",
        }
    if "luis rené, tienes razón" in name:
        return {
            "classification": "MODEL_TRAINING_ADAPTER_SOURCE",
            "lane": "obsai",
            "intake_action": "REVIEW_BEFORE_MODEL_WORK",
            "target": "Claudio model-router docs and future training backlog",
            "notes": "Fine-tuning/adapters source with heavy dependencies. Do not run or claim model improvement without measured evals.",
        }
    if "sí, luis rené. podemos abordar ambo" in name:
        return {
            "classification": "TERMINAL_GUARD_AND_ANTIGRAVITY_RESEARCH_SOURCE",
            "lane": "research-boundary",
            "intake_action": "SECURITY_GATE_AND_CLAIM_REVIEW",
            "target": "ResidueOS TerminalGuard backlog and research-only antigravity notes",
            "notes": "Contains TerminalGuard/action-gate security ideas plus antigravity framing. Public language must separate safety tooling from speculative physics.",
        }
    if "tu mensaje se cortó" in name:
        return {
            "classification": "OBS_INFO_KERNEL_CODE_CONTINUATION",
            "lane": "research-boundary",
            "intake_action": "READ_REVIEW_TEST_BEFORE_IMPORT",
            "target": "research/obs-info-kernel",
            "notes": "Continuation source for topology/compressor code. Review dependencies and tests before importing.",
        }
    if "==================================" in name:
        return {
            "classification": "OBSERVACIONISMO_SYNTHESIS_BUNDLE",
            "lane": "research-boundary",
            "intake_action": "RESEARCH_ONLY_WITH_CLAIM_BOUNDARY",
            "target": "claudio/memory_vault and research/",
            "notes": "Mixed synthesis bundle including Gemma, Maat/PSI and social/system framing. Use as categorized source, not raw public text.",
        }
    if "neurostate" in name:
        return {
            "classification": "NEUROSTATE_SOURCE",
            "lane": "duat-neurostate-residueos",
            "intake_action": "TECHNICAL_CARD_AND_SPLIT",
            "target": "claudio/memory_vault and future neurostate prototype",
            "notes": "Neurostate source or bundle. Requires UI/runtime split and privacy/claims review.",
        }
    if "gemma" in name or "modelo" in name or "modelos de mundo" in name or "motor gemma" in name:
        return {
            "classification": "GEMMA_OBSERVACIONISMO_MODEL_SOURCE",
            "lane": "obsai",
            "intake_action": "MODEL_ROUTING_BACKLOG_ONLY",
            "target": "packages/open-dev/obsai-core and Claudio model-router docs",
            "notes": "Model-routing/adapters source. No model-performance claims until measured on this host.",
        }
    if "patent" in name or "patente" in name or "ferritin" in name or name == "files.zip":
        return {
            "classification": "PATENT_PATTERN_RESEARCH_SOURCE",
            "lane": "research-boundary",
            "intake_action": "LICENSE_AND_CLAIM_REVIEW",
            "target": "research/ and claims boundary docs",
            "notes": "Patent/pattern research. Keep as analysis until legal/license and claim review are complete.",
        }
    if "residue" in name or "actiongate" in name or "threshold" in name:
        return {
            "classification": "RESIDUEOS_GATE_SOURCE",
            "lane": "residueos",
            "intake_action": "SELECTIVE_ABSORPTION_ONLY",
            "target": "packages/open-dev/residueos",
            "notes": "Gate/threshold source. Thresholds remain DEMO_ONLY until calibrated.",
        }
    if "firma_conductual" in name:
        return {
            "classification": "BEHAVIORAL_SIGNATURE_DEMO",
            "lane": "research-boundary",
            "intake_action": "PRIVACY_REVIEW_BEFORE_USE",
            "target": "docs/privacy and research/",
            "notes": "Behavioral-signature demo. Requires privacy and biometric-risk language before use.",
        }
    if "medioevo" in name or "manuscrito" in name:
        return {
            "classification": "BOOKS_EDITORIAL_OR_PRIVATE_SOURCE",
            "lane": "lore",
            "intake_action": "CLASSIFY_BEFORE_EXTRACTION",
            "target": "books/editorial or game-private only",
            "notes": "MEDIOEVO/editorial source. Do not publish raw or mix with open-dev packages.",
        }
    if "app que no existe" in name or "amigo" in name or "recomiende" in name:
        return {
            "classification": "PRODUCT_STRATEGY_SOURCE",
            "lane": "strategy",
            "intake_action": "BACKLOG_AND_COMMERCIAL_SPLIT",
            "target": "docs/business and docs/developer",
            "notes": "Product/monetization strategy source. Convert to low-claim roadmap and private patrimony plan.",
        }
    if suffix in {".py", ".rs", ".ts", ".js"} or "codigo" in name or "código" in name or "code" in name:
        return {
            "classification": "EXTERNAL_CODE_PROTOTYPE",
            "lane": "research-boundary",
            "intake_action": "READ_REVIEW_TEST_BEFORE_IMPORT",
            "target": "research/ or package-specific experiments",
            "notes": "Code prototype. Review dependencies, side effects and claims before copying.",
        }
    if "observ" in name or "psi" in name or "lg" in name or "integraci" in name or "honesto" in name or "formal" in name or "matem" in name or "extraordinariament" in name:
        return {
            "classification": "OBSERVACIONISMO_RESEARCH_SYNTHESIS",
            "lane": "research-boundary",
            "intake_action": "RESEARCH_ONLY_WITH_CLAIM_BOUNDARY",
            "target": "claudio/memory_vault and research/",
            "notes": "Observacionismo research synthesis. Preserve evidence/inference/unknown labels.",
        }
    return {
        "classification": "REVIEW_REQUIRED_DOWNLOAD",
        "lane": "cleanup",
        "intake_action": "HOLD_WITH_TECHNICAL_CARD_BEFORE_USE",
        "target": "curador review and memory_vault index",
        "notes": "No specific rule matched. Keep out of public packages until a technical card records evidence, inference and unknowns.",
    }


def additional_download_records(known_paths: set[Path], hash_files: bool) -> list[dict[str, Any]]:
    records: list[dict[str, Any]] = []
    if not DOWNLOADS.exists():
        return records
    try:
        children = sorted(DOWNLOADS.iterdir(), key=lambda path: path.name.lower())
    except OSError:
        return records
    for child in children:
        try:
            resolved = child.resolve()
        except OSError:
            resolved = child
        if resolved in known_paths:
            continue
        classification = classify_additional_download(child)
        record = {
            "path": str(child),
            "exists": child.exists(),
            "kind": "directory" if child.is_dir() else "file",
            **classification,
        }
        if child.is_file():
            try:
                stat = child.stat()
            except OSError as exc:
                record["stat_error"] = str(exc)
            else:
                record["bytes"] = stat.st_size
                record["last_write_time_utc"] = datetime.fromtimestamp(stat.st_mtime, timezone.utc).isoformat()
                if child.suffix.lower() in TEXT_SUFFIXES and stat.st_size <= 5_000_000:
                    record["line_count"] = count_text_lines(child)
                if hash_files:
                    try:
                        record["sha256"] = sha256_file(child)
                    except OSError as exc:
                        record["sha256_error"] = str(exc)
        records.append(record)
    return records


def md_bool(value: bool) -> str:
    return "yes" if value else "no"


def short_hash(record: dict[str, Any]) -> str:
    value = record.get("sha256")
    if isinstance(value, str):
        return value[:16]
    return record.get("sha256_error", "")


def render_markdown(register: dict[str, Any]) -> str:
    lines = [
        "# SOURCE_INTAKE_REGISTER",
        "",
        f"Generated UTC: `{register['generated_at_utc']}`",
        "",
        "Status: active control document. This is a manifest of sources, not permission to publish.",
        "",
        "## Rules",
        "",
    ]
    for rule in register["rules"]:
        lines.append(f"- {rule}")

    lines.extend(
        [
            "",
            "## Downloads Intake",
            "",
            "| source | exists | bytes | lines | sha256_prefix | classification | lane | intake_action | target |",
            "|---|---:|---:|---:|---|---|---|---|---|",
        ]
    )
    for record in register["downloads"]:
        bytes_value = record.get("bytes", "")
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{record['path']}`",
                    md_bool(bool(record["exists"])),
                    str(bytes_value),
                    str(record.get("line_count", "")),
                    short_hash(record),
                    record["classification"],
                    record["lane"],
                    record["intake_action"],
                    record["target"],
                ]
            )
            + " |"
        )

    decision_records = [
        record
        for record in register["downloads"]
        if record.get("decision") or record.get("risks")
    ]
    if decision_records:
        lines.extend(
            [
                "",
                "## Source Decisions And Risks",
                "",
                "| source | decision | risks | notes |",
                "|---|---|---|---|",
            ]
        )
        for record in decision_records:
            risks = "; ".join(str(item) for item in record.get("risks", []))
            lines.append(
                "| "
                + " | ".join(
                    [
                        f"`{record['path']}`",
                        str(record.get("decision", "")),
                        risks,
                        str(record.get("notes", "")),
                    ]
                )
                + " |"
            )

    lines.extend(
        [
            "",
            "## Additional Classified Downloads",
            "",
            "| source | kind | exists | bytes | lines | sha256_prefix | classification | lane | intake_action | target |",
            "|---|---|---:|---:|---:|---|---|---|---|---|",
        ]
    )
    for record in register["additional_downloads"]:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{record['path']}`",
                    record["kind"],
                    md_bool(bool(record["exists"])),
                    str(record.get("bytes", "")),
                    str(record.get("line_count", "")),
                    short_hash(record),
                    record["classification"],
                    record["lane"],
                    record["intake_action"],
                    record["target"],
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## External Roots",
            "",
            "| root | exists | child_dirs | child_files | git_repo | classification | lane | intake_action |",
            "|---|---:|---:|---:|---:|---|---|---|",
        ]
    )
    for record in register["external_roots"]:
        lines.append(
            "| "
            + " | ".join(
                [
                    f"`{record['path']}`",
                    md_bool(bool(record["exists"])),
                    str(record.get("child_dirs", "")),
                    str(record.get("child_files", "")),
                    md_bool(bool(record.get("is_git_repo", False))),
                    record["classification"],
                    record["lane"],
                    record["intake_action"],
                ]
            )
            + " |"
        )

    lines.extend(
        [
            "",
            "## Lane Decisions",
            "",
            "| lane | allowed intake | hard boundary |",
            "|---|---|---|",
            "| residueos | Extract only gate/API/store concepts into `apps/residueos`; migrate demo JSON stores to SQLite before product closure. | Calibration and confusion matrix stay `DEMO_ONLY` until a real dataset exists. |",
            "| obsai | Extract metrics, action gate and CLI primitives into `packages/obsai-core`. | No claims of consciousness, physics proof or solved cosmology. |",
            "| lore | Extract canon-to-data fixtures and schemas with evidence fields. | Full books, private lore and game data do not enter open packages. |",
            "| rpg-private | Use manifests, hashes and private repo discipline before edits. | No public packaging, no free release, no source mixing. |",
            "| publishing | Use manifests and checksums for books/assets/products. | No publication claim without Gumroad/web verification. |",
            "| research-boundary | Store as `RESEARCH_ONLY` with falsifier or `PREDICTION_REQUIRED`. | No product copy can imply validated science. |",
            "| github-public-sanitized | Convert only reviewed architecture, code and docs into clean repos with `CLAIMS.md`, `PRIVATE_EXCLUSIONS.md`, tests and synthetic fixtures. | No raw Downloads text, local paths, secrets, private family context, RPG, full books, vendors or strong scientific claims. |",
            "| secrets | Track redacted evidence and staging exclusions. | Never print secret values, stage secret files or rely on ignore rules as publication safety. |",
            "",
            "## Residue",
            "",
            "- This register lists ZIPs by hash and source contract; use a focused extractor before importing code.",
            "- Duplicate files in `_ARCHIVO_OBSERVACIONISMO_DUPLICADOS_2026-04-29` are kept as manifest-only evidence.",
            "- Deep recursive counts for `E:\\` roots are intentionally not performed here to avoid slow or unsafe broad scans.",
        ]
    )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description="Create a source-intake register for external MEDIOEVO/Observacionismo sources.")
    add_common_args(parser)
    parser.add_argument("--hash", action="store_true", help="hash known file sources")
    parser.add_argument("--write", action="store_true", help="write SOURCE_INTAKE_REGISTER.md and source_intake_register.json")
    args = parser.parse_args()
    validate_root_arg(args)

    register = build_register(hash_files=args.hash)
    if args.write:
        (ROOT / "SOURCE_INTAKE_REGISTER.md").write_text(render_markdown(register), encoding="utf-8")
        (ROOT / "source_intake_register.json").write_text(json.dumps(register, indent=2, ensure_ascii=False), encoding="utf-8")
        print("wrote SOURCE_INTAKE_REGISTER.md")
        print("wrote source_intake_register.json")
    else:
        print_json(register)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
